export type Language = { name: string; native: string; popular?: boolean };

/**
 * Curated world-language list: every major living language plus broad
 * regional coverage, each with its verified native endonym. Anything not
 * listed can still be typed via the selector's "Other language" option —
 * the translation backend accepts any language name.
 */
export const languages: Language[] = [
  // ── India (priority) ──
  { name: 'Telugu', native: 'తెలుగు', popular: true },
  { name: 'Tamil', native: 'தமிழ்', popular: true },
  { name: 'Hindi', native: 'हिन्दी', popular: true },
  { name: 'Kannada', native: 'ಕನ್ನಡ', popular: true },
  { name: 'Malayalam', native: 'മലയാളം' },
  { name: 'Bengali', native: 'বাংলা' },
  { name: 'Marathi', native: 'मराठी' },
  { name: 'Gujarati', native: 'ગુજરાતી' },
  { name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { name: 'Urdu', native: 'اردو' },
  { name: 'Odia', native: 'ଓଡ଼ିଆ' },
  { name: 'Assamese', native: 'অসমীয়া' },
  { name: 'Sanskrit', native: 'संस्कृतम्' },
  { name: 'Nepali', native: 'नेपाली' },
  { name: 'Konkani', native: 'कोंकणी' },
  { name: 'Maithili', native: 'मैथिली' },
  { name: 'Dogri', native: 'डोगरी' },
  { name: 'Kashmiri', native: 'कॉशुर' },
  { name: 'Sindhi', native: 'سنڌي' },
  { name: 'Santali', native: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { name: 'Manipuri', native: 'মৈতৈ' },
  { name: 'Bodo', native: 'बड़ो' },
  { name: 'Sinhala', native: 'සිංහල' },
  { name: 'Dhivehi', native: 'ދިވެހި' },
  // ── South / Central Asia ──
  { name: 'Persian', native: 'فارسی' },
  { name: 'Dari', native: 'دری' },
  { name: 'Pashto', native: 'پښتو' },
  { name: 'Kurdish (Kurmanji)', native: 'Kurdî' },
  { name: 'Kurdish (Sorani)', native: 'کوردی' },
  { name: 'Tibetan', native: 'བོད་སྐད་' },
  { name: 'Dzongkha', native: 'རྫོང་ཁ' },
  { name: 'Kazakh', native: 'Қазақша' },
  { name: 'Uzbek', native: "O'zbek" },
  { name: 'Kyrgyz', native: 'Кыргызча' },
  { name: 'Turkmen', native: 'Türkmençe' },
  { name: 'Tajik', native: 'Тоҷикӣ' },
  { name: 'Mongolian', native: 'Монгол' },
  { name: 'Uyghur', native: 'ئۇيغۇر' },
  { name: 'Tatar', native: 'Татарча' },
  { name: 'Sakha', native: 'Саха тыла' },
  // ── Middle East ──
  { name: 'Arabic', native: 'العربية', popular: true },
  { name: 'Hebrew', native: 'עברית' },
  { name: 'Turkish', native: 'Türkçe' },
  { name: 'Azerbaijani', native: 'Azərbaycan' },
  { name: 'Georgian', native: 'ქართული' },
  { name: 'Armenian', native: 'Հայերեն' },
  { name: 'Amharic', native: 'አማርኛ' },
  { name: 'Tigrinya', native: 'ትግርኛ' },
  { name: 'Somali', native: 'Soomaali' },
  // ── East Asia ──
  { name: 'Chinese (Simplified)', native: '简体中文', popular: true },
  { name: 'Chinese (Cantonese)', native: '粵語' },
  { name: 'Japanese', native: '日本語', popular: true },
  { name: 'Korean', native: '한국어' },
  // ── Southeast Asia ──
  { name: 'Vietnamese', native: 'Tiếng Việt' },
  { name: 'Thai', native: 'ไทย' },
  { name: 'Lao', native: 'ລາວ' },
  { name: 'Khmer', native: 'ខ្មែរ' },
  { name: 'Burmese', native: 'မြန်မာ' },
  { name: 'Indonesian', native: 'Bahasa Indonesia' },
  { name: 'Malay', native: 'Bahasa Melayu' },
  { name: 'Tagalog', native: 'Tagalog' },
  { name: 'Cebuano', native: 'Cebuano' },
  { name: 'Javanese', native: 'Basa Jawa' },
  { name: 'Sundanese', native: 'Basa Sunda' },
  { name: 'Hmong', native: 'Hmoob' },
  // ── Europe (West / South) ──
  { name: 'English', native: 'English', popular: true },
  { name: 'Spanish', native: 'Español', popular: true },
  { name: 'French', native: 'Français' },
  { name: 'German', native: 'Deutsch' },
  { name: 'Italian', native: 'Italiano' },
  { name: 'Portuguese', native: 'Português' },
  { name: 'Dutch', native: 'Nederlands' },
  { name: 'Greek', native: 'Ελληνικά' },
  { name: 'Catalan', native: 'Català' },
  { name: 'Galician', native: 'Galego' },
  { name: 'Basque', native: 'Euskara' },
  { name: 'Welsh', native: 'Cymraeg' },
  { name: 'Irish', native: 'Gaeilge' },
  { name: 'Breton', native: 'Brezhoneg' },
  { name: 'Occitan', native: 'Occitan' },
  { name: 'Luxembourgish', native: 'Lëtzebuergesch' },
  { name: 'Frisian', native: 'Frysk' },
  { name: 'Maltese', native: 'Malti' },
  { name: 'Albanian', native: 'Shqip' },
  { name: 'Romanian', native: 'Română' },
  // ── Europe (North / Central / East) ──
  { name: 'Polish', native: 'Polski' },
  { name: 'Czech', native: 'Čeština' },
  { name: 'Slovak', native: 'Slovenčina' },
  { name: 'Hungarian', native: 'Magyar' },
  { name: 'Bulgarian', native: 'Български' },
  { name: 'Serbian', native: 'Српски' },
  { name: 'Croatian', native: 'Hrvatski' },
  { name: 'Bosnian', native: 'Bosanski' },
  { name: 'Slovenian', native: 'Slovenščina' },
  { name: 'Macedonian', native: 'Македонски' },
  { name: 'Russian', native: 'Русский' },
  { name: 'Ukrainian', native: 'Українська' },
  { name: 'Belarusian', native: 'Беларуская' },
  { name: 'Lithuanian', native: 'Lietuvių' },
  { name: 'Latvian', native: 'Latviešu' },
  { name: 'Estonian', native: 'Eesti' },
  { name: 'Finnish', native: 'Suomi' },
  { name: 'Swedish', native: 'Svenska' },
  { name: 'Norwegian', native: 'Norsk' },
  { name: 'Danish', native: 'Dansk' },
  { name: 'Icelandic', native: 'Íslenska' },
  { name: 'Faroese', native: 'Føroyskt' },
  { name: 'Romansh', native: 'Rumantsch' },
  // ── Africa ──
  { name: 'Swahili', native: 'Kiswahili' },
  { name: 'Hausa', native: 'Hausa' },
  { name: 'Yoruba', native: 'Yorùbá' },
  { name: 'Igbo', native: 'Igbo' },
  { name: 'Zulu', native: 'isiZulu' },
  { name: 'Xhosa', native: 'isiXhosa' },
  { name: 'Shona', native: 'chiShona' },
  { name: 'Sesotho', native: 'Sesotho' },
  { name: 'Setswana', native: 'Setswana' },
  { name: 'Tsonga', native: 'Xitsonga' },
  { name: 'Venda', native: 'Tshivenda' },
  { name: 'Swati', native: 'SiSwati' },
  { name: 'Afrikaans', native: 'Afrikaans' },
  { name: 'Malagasy', native: 'Malagasy' },
  { name: 'Kinyarwanda', native: 'Kinyarwanda' },
  { name: 'Luganda', native: 'Luganda' },
  { name: 'Oromo', native: 'Afaan Oromoo' },
  { name: 'Akan', native: 'Twi' },
  { name: 'Ewe', native: 'Eʋegbe' },
  { name: 'Wolof', native: 'Wolof' },
  { name: 'Bambara', native: 'Bamanankan' },
  { name: 'Fulani', native: 'Fulfulde' },
  { name: 'Lingala', native: 'Lingála' },
  { name: 'Chichewa', native: 'Chichewa' },
  // ── Pacific ──
  { name: 'Maori', native: 'Te Reo Māori' },
  { name: 'Hawaiian', native: 'ʻŌlelo Hawaiʻi' },
  { name: 'Samoan', native: 'Gagana Samoa' },
  // ── Americas ──
  { name: 'Quechua', native: 'Runasimi' },
  { name: 'Guarani', native: "Avañe'ẽ" },
  { name: 'Aymara', native: 'Aymar aru' },
  { name: 'Nahuatl', native: 'Nahuatl' },
  { name: 'Haitian Creole', native: 'Kreyòl' },
  // ── Constructed ──
  { name: 'Esperanto', native: 'Esperanto' },
];

export const popularLanguages = languages.filter((l) => l.popular);

/** Display info for any selected value, including custom-typed languages. */
export function describeLanguage(value: string): { native: string; name: string } {
  const found = languages.find((l) => l.name === value);
  if (found) return { native: found.native, name: found.name };
  return { native: value, name: value };
}
