/**
 * Product-facing catalog from the official NLLB/FLORES tokenizer inventory.
 *
 * One downloaded NLLB model can translate between every entry here. Coverage
 * and quality still vary by language and direction, so the UI describes this
 * as broad offline utility rather than equal quality for every language.
 * Keep codes aligned with:
 * https://github.com/huggingface/transformers/blob/main/src/transformers/models/nllb/tokenization_nllb.py
 */
export type NllbLanguage = {
  name: string;
  native: string;
  code: string;
  popular?: boolean;
};

export const NLLB_LANGUAGE_CATALOG: NllbLanguage[] = [
  // India and nearby languages
  { name: 'Telugu', native: 'తెలుగు', code: 'tel_Telu', popular: true },
  { name: 'Tamil', native: 'தமிழ்', code: 'tam_Taml', popular: true },
  { name: 'Hindi', native: 'हिन्दी', code: 'hin_Deva', popular: true },
  { name: 'Kannada', native: 'ಕನ್ನಡ', code: 'kan_Knda', popular: true },
  { name: 'Malayalam', native: 'മലയാളം', code: 'mal_Mlym' },
  { name: 'Bengali', native: 'বাংলা', code: 'ben_Beng' },
  { name: 'Marathi', native: 'मराठी', code: 'mar_Deva' },
  { name: 'Gujarati', native: 'ગુજરાતી', code: 'guj_Gujr' },
  { name: 'Punjabi', native: 'ਪੰਜਾਬੀ', code: 'pan_Guru' },
  { name: 'Urdu', native: 'اردو', code: 'urd_Arab' },
  { name: 'Odia', native: 'ଓଡ଼ିଆ', code: 'ory_Orya' },
  { name: 'Assamese', native: 'অসমীয়া', code: 'asm_Beng' },
  { name: 'Sanskrit', native: 'संस्कृतम्', code: 'san_Deva' },
  { name: 'Nepali', native: 'नेपाली', code: 'npi_Deva' },
  { name: 'Maithili', native: 'मैथिली', code: 'mai_Deva' },
  { name: 'Bhojpuri', native: 'भोजपुरी', code: 'bho_Deva' },
  { name: 'Kashmiri', native: 'कॉशुर', code: 'kas_Arab' },
  { name: 'Santali', native: 'ᱥᱟᱱᱛᱟᱲᱤ', code: 'sat_Beng' },
  { name: 'Sinhala', native: 'සිංහල', code: 'sin_Sinh' },

  // Europe
  { name: 'English', native: 'English', code: 'eng_Latn', popular: true },
  { name: 'Spanish', native: 'Español', code: 'spa_Latn', popular: true },
  { name: 'French', native: 'Français', code: 'fra_Latn' },
  { name: 'German', native: 'Deutsch', code: 'deu_Latn' },
  { name: 'Italian', native: 'Italiano', code: 'ita_Latn' },
  { name: 'Portuguese', native: 'Português', code: 'por_Latn' },
  { name: 'Dutch', native: 'Nederlands', code: 'nld_Latn' },
  { name: 'Greek', native: 'Ελληνικά', code: 'ell_Grek' },
  { name: 'Catalan', native: 'Català', code: 'cat_Latn' },
  { name: 'Basque', native: 'Euskara', code: 'eus_Latn' },
  { name: 'Welsh', native: 'Cymraeg', code: 'cym_Latn' },
  { name: 'Irish', native: 'Gaeilge', code: 'gle_Latn' },
  { name: 'Albanian', native: 'Shqip', code: 'als_Latn' },
  { name: 'Romanian', native: 'Română', code: 'ron_Latn' },
  { name: 'Polish', native: 'Polski', code: 'pol_Latn' },
  { name: 'Czech', native: 'Čeština', code: 'ces_Latn' },
  { name: 'Slovak', native: 'Slovenčina', code: 'slk_Latn' },
  { name: 'Hungarian', native: 'Magyar', code: 'hun_Latn' },
  { name: 'Bulgarian', native: 'Български', code: 'bul_Cyrl' },
  { name: 'Serbian', native: 'Српски', code: 'srp_Cyrl' },
  { name: 'Croatian', native: 'Hrvatski', code: 'hrv_Latn' },
  { name: 'Slovenian', native: 'Slovenščina', code: 'slv_Latn' },
  { name: 'Macedonian', native: 'Македонски', code: 'mkd_Cyrl' },
  { name: 'Russian', native: 'Русский', code: 'rus_Cyrl' },
  { name: 'Ukrainian', native: 'Українська', code: 'ukr_Cyrl' },
  { name: 'Lithuanian', native: 'Lietuvių', code: 'lit_Latn' },
  { name: 'Latvian', native: 'Latviešu', code: 'lvs_Latn' },
  { name: 'Estonian', native: 'Eesti', code: 'est_Latn' },
  { name: 'Finnish', native: 'Suomi', code: 'fin_Latn' },
  { name: 'Swedish', native: 'Svenska', code: 'swe_Latn' },
  { name: 'Norwegian', native: 'Norsk', code: 'nob_Latn' },
  { name: 'Danish', native: 'Dansk', code: 'dan_Latn' },

  // Middle East and Central Asia
  { name: 'Arabic', native: 'العربية', code: 'arb_Arab', popular: true },
  { name: 'Persian', native: 'فارسی', code: 'pes_Arab' },
  { name: 'Pashto', native: 'پښتو', code: 'pbt_Arab' },
  { name: 'Kurdish (Kurmanji)', native: 'Kurdî', code: 'kmr_Latn' },
  { name: 'Kazakh', native: 'Қазақша', code: 'kaz_Cyrl' },
  { name: 'Uzbek', native: "O'zbek", code: 'uzn_Latn' },
  { name: 'Kyrgyz', native: 'Кыргызча', code: 'kir_Cyrl' },
  { name: 'Tajik', native: 'Тоҷикӣ', code: 'tgk_Cyrl' },
  { name: 'Mongolian', native: 'Монгол', code: 'khk_Cyrl' },
  { name: 'Uyghur', native: 'ئۇيغۇر', code: 'uig_Arab' },
  { name: 'Turkish', native: 'Türkçe', code: 'tur_Latn' },
  { name: 'Azerbaijani', native: 'Azərbaycan', code: 'azj_Latn' },
  { name: 'Georgian', native: 'ქართული', code: 'kat_Geor' },
  { name: 'Armenian', native: 'Հայերեն', code: 'hye_Armn' },
  { name: 'Hebrew', native: 'עברית', code: 'heb_Hebr' },

  // East and Southeast Asia
  { name: 'Chinese (Simplified)', native: '简体中文', code: 'zho_Hans', popular: true },
  { name: 'Chinese (Traditional)', native: '繁體中文', code: 'zho_Hant' },
  { name: 'Chinese (Cantonese)', native: '粵語', code: 'yue_Hant' },
  { name: 'Japanese', native: '日本語', code: 'jpn_Jpan', popular: true },
  { name: 'Korean', native: '한국어', code: 'kor_Hang' },
  { name: 'Vietnamese', native: 'Tiếng Việt', code: 'vie_Latn' },
  { name: 'Thai', native: 'ไทย', code: 'tha_Thai' },
  { name: 'Lao', native: 'ລາວ', code: 'lao_Laoo' },
  { name: 'Khmer', native: 'ខ្មែរ', code: 'khm_Khmr' },
  { name: 'Burmese', native: 'မြန်မာ', code: 'mya_Mymr' },
  { name: 'Indonesian', native: 'Bahasa Indonesia', code: 'ind_Latn' },
  { name: 'Malay', native: 'Bahasa Melayu', code: 'zsm_Latn' },
  { name: 'Tagalog', native: 'Tagalog', code: 'tgl_Latn' },
  { name: 'Cebuano', native: 'Cebuano', code: 'ceb_Latn' },
  { name: 'Javanese', native: 'Basa Jawa', code: 'jav_Latn' },
  { name: 'Sundanese', native: 'Basa Sunda', code: 'sun_Latn' },

  // Africa and the Americas
  { name: 'Amharic', native: 'አማርኛ', code: 'amh_Ethi' },
  { name: 'Swahili', native: 'Kiswahili', code: 'swh_Latn' },
  { name: 'Hausa', native: 'Hausa', code: 'hau_Latn' },
  { name: 'Yoruba', native: 'Yorùbá', code: 'yor_Latn' },
  { name: 'Igbo', native: 'Igbo', code: 'ibo_Latn' },
  { name: 'Zulu', native: 'isiZulu', code: 'zul_Latn' },
  { name: 'Xhosa', native: 'isiXhosa', code: 'xho_Latn' },
  { name: 'Shona', native: 'chiShona', code: 'sna_Latn' },
  { name: 'Afrikaans', native: 'Afrikaans', code: 'afr_Latn' },
  { name: 'Somali', native: 'Soomaali', code: 'som_Latn' },
  { name: 'Oromo', native: 'Afaan Oromoo', code: 'gaz_Latn' },
  { name: 'Akan', native: 'Twi', code: 'aka_Latn' },
  { name: 'Ewe', native: 'Eʋegbe', code: 'ewe_Latn' },
  { name: 'Wolof', native: 'Wolof', code: 'wol_Latn' },
  { name: 'Haitian Creole', native: 'Kreyòl', code: 'hat_Latn' },
  { name: 'Quechua', native: 'Runasimi', code: 'quy_Latn' },
  { name: 'Guarani', native: "Avañe'ẽ", code: 'grn_Latn' },
  { name: 'Esperanto', native: 'Esperanto', code: 'epo_Latn' },

  // Additional official NLLB/FLORES entries. These are intentionally kept in
  // the same catalog so every downloaded language shares one verified model.
  { name: 'Acehnese (Arabic)', native: 'بهاس اچيه', code: 'ace_Arab' },
  { name: 'Acehnese (Latin)', native: 'Bahsa Acèh', code: 'ace_Latn' },
  { name: 'Mesopotamian Arabic', native: 'العربية العراقية', code: 'acm_Arab' },
  { name: 'Taʿizzi-Adeni Arabic', native: 'العربية العدنية', code: 'acq_Arab' },
  { name: 'Tunisian Arabic', native: 'العربية التونسية', code: 'aeb_Arab' },
  { name: 'South Levantine Arabic', native: 'العربية الشامية', code: 'ajp_Arab' },
  { name: 'North Levantine Arabic', native: 'العربية الشامية', code: 'apc_Arab' },
  { name: 'Najdi Arabic', native: 'العربية النجدية', code: 'ars_Arab' },
  { name: 'Moroccan Arabic', native: 'الدارجة', code: 'ary_Arab' },
  { name: 'Egyptian Arabic', native: 'العربية المصرية', code: 'arz_Arab' },
  { name: 'Asturian', native: 'Asturianu', code: 'ast_Latn' },
  { name: 'Awadhi', native: 'अवधी', code: 'awa_Deva' },
  { name: 'Aymara', native: 'Aymar aru', code: 'ayr_Latn' },
  { name: 'North Azerbaijani (Arabic)', native: 'آذری', code: 'azb_Arab' },
  { name: 'Bashkir', native: 'Башҡортса', code: 'bak_Cyrl' },
  { name: 'Bambara', native: 'Bamanankan', code: 'bam_Latn' },
  { name: 'Balinese', native: 'Basa Bali', code: 'ban_Latn' },
  { name: 'Belarusian', native: 'Беларуская', code: 'bel_Cyrl' },
  { name: 'Bemba', native: 'Ichibemba', code: 'bem_Latn' },
  { name: 'Banjarese (Arabic)', native: 'بهاس بنجر', code: 'bjn_Arab' },
  { name: 'Banjarese (Latin)', native: 'Bahasa Banjar', code: 'bjn_Latn' },
  { name: 'Tibetan', native: 'བོད་སྐད་', code: 'bod_Tibt' },
  { name: 'Bosnian', native: 'Bosanski', code: 'bos_Latn' },
  { name: 'Buginese', native: 'ᨅᨔ ᨕᨘᨁᨗ', code: 'bug_Latn' },
  { name: 'Chokwe', native: 'Cokwe', code: 'cjk_Latn' },
  { name: 'Central Kurdish', native: 'کوردیی ناوەندی', code: 'ckb_Arab' },
  { name: 'Crimean Tatar', native: 'Qırımtatarca', code: 'crh_Latn' },
  { name: 'Dinka', native: 'Thuɔŋjäŋ', code: 'dik_Latn' },
  { name: 'Dyula', native: 'Julakan', code: 'dyu_Latn' },
  { name: 'Dzongkha', native: 'རྫོང་ཁ', code: 'dzo_Tibt' },
  { name: 'Faroese', native: 'Føroyskt', code: 'fao_Latn' },
  { name: 'Fijian', native: 'Vosa Vakaviti', code: 'fij_Latn' },
  { name: 'Fon', native: 'Fɔngbè', code: 'fon_Latn' },
  { name: 'Friulian', native: 'Furlan', code: 'fur_Latn' },
  { name: 'Fulfulde', native: 'Fulfulde', code: 'fuv_Latn' },
  { name: 'Scottish Gaelic', native: 'Gàidhlig', code: 'gla_Latn' },
  { name: 'Galician', native: 'Galego', code: 'glg_Latn' },
  { name: 'Chhattisgarhi', native: 'छत्तीसगढ़ी', code: 'hne_Deva' },
  { name: 'Ilocano', native: 'Ilokano', code: 'ilo_Latn' },
  { name: 'Icelandic', native: 'Íslenska', code: 'isl_Latn' },
  { name: 'Kabyle', native: 'Taqbaylit', code: 'kab_Latn' },
  { name: 'Kachin', native: 'Jinghpaw', code: 'kac_Latn' },
  { name: 'Kamba', native: 'Kikamba', code: 'kam_Latn' },
  { name: 'Kashmiri (Devanagari)', native: 'कॉशुर', code: 'kas_Deva' },
  { name: 'Central Kanuri (Arabic)', native: 'کَنُوری', code: 'knc_Arab' },
  { name: 'Central Kanuri (Latin)', native: 'Kanuri', code: 'knc_Latn' },
  { name: 'Kabiyè', native: 'Kabyè', code: 'kbp_Latn' },
  { name: 'Kabuverdianu', native: 'Kabuverdianu', code: 'kea_Latn' },
  { name: 'Kikuyu', native: 'Gĩkũyũ', code: 'kik_Latn' },
  { name: 'Kinyarwanda', native: 'Ikinyarwanda', code: 'kin_Latn' },
  { name: 'Kimbundu', native: 'Kimbundu', code: 'kmb_Latn' },
  { name: 'Kongo', native: 'Kikongo', code: 'kon_Latn' },
  { name: 'Ligurian', native: 'Lìgure', code: 'lij_Latn' },
  { name: 'Limburgish', native: 'Limburgs', code: 'lim_Latn' },
  { name: 'Lingala', native: 'Lingála', code: 'lin_Latn' },
  { name: 'Lombard', native: 'Lumbaart', code: 'lmo_Latn' },
  { name: 'Latgalian', native: 'Latgalīšu volūda', code: 'ltg_Latn' },
  { name: 'Luxembourgish', native: 'Lëtzebuergesch', code: 'ltz_Latn' },
  { name: 'Luba-Katanga', native: 'Tshiluba', code: 'lua_Latn' },
  { name: 'Luganda', native: 'Luganda', code: 'lug_Latn' },
  { name: 'Luo', native: 'Dholuo', code: 'luo_Latn' },
  { name: 'Mizo', native: 'Mizo ṭawng', code: 'lus_Latn' },
  { name: 'Magahi', native: 'मगही', code: 'mag_Deva' },
  { name: 'Minangkabau', native: 'Baso Minangkabau', code: 'min_Latn' },
  { name: 'Plateau Malagasy', native: 'Malagasy', code: 'plt_Latn' },
  { name: 'Maltese', native: 'Malti', code: 'mlt_Latn' },
  { name: 'Meitei', native: 'মৈতৈ', code: 'mni_Beng' },
  { name: 'Mossi', native: 'Mòoré', code: 'mos_Latn' },
  { name: 'Māori', native: 'Te Reo Māori', code: 'mri_Latn' },
  { name: 'Norwegian Nynorsk', native: 'Nynorsk', code: 'nno_Latn' },
  { name: 'Northern Sotho', native: 'Sepedi', code: 'nso_Latn' },
  { name: 'Nuer', native: 'Thok Naath', code: 'nus_Latn' },
  { name: 'Nyanja', native: 'Chichewa', code: 'nya_Latn' },
  { name: 'Occitan', native: 'Occitan', code: 'oci_Latn' },
  { name: 'Pangasinan', native: 'Pangasinan', code: 'pag_Latn' },
  { name: 'Papiamento', native: 'Papiamentu', code: 'pap_Latn' },
  { name: 'Dari', native: 'دری', code: 'prs_Arab' },
  { name: 'Rundi', native: 'Ikirundi', code: 'run_Latn' },
  { name: 'Sango', native: 'Sängö', code: 'sag_Latn' },
  { name: 'Sicilian', native: 'Sicilianu', code: 'scn_Latn' },
  { name: 'Shan', native: 'ၽႃႇသႃႇတႆး', code: 'shn_Mymr' },
  { name: 'Samoan', native: 'Gagana Samoa', code: 'smo_Latn' },
  { name: 'Sindhi', native: 'سنڌي', code: 'snd_Arab' },
  { name: 'Southern Sotho', native: 'Sesotho', code: 'sot_Latn' },
  { name: 'Sardinian', native: 'Sardu', code: 'srd_Latn' },
  { name: 'Swati', native: 'SiSwati', code: 'ssw_Latn' },
  { name: 'Silesian', native: 'Ślōnskŏ gŏdka', code: 'szl_Latn' },
  { name: 'Tatar', native: 'Татарча', code: 'tat_Cyrl' },
  { name: 'Tigrinya', native: 'ትግርኛ', code: 'tir_Ethi' },
  { name: 'Tamasheq (Latin)', native: 'ⵜⵎⴰⵣⵉⵖⵜ', code: 'taq_Latn' },
  { name: 'Tamasheq (Tifinagh)', native: 'ⵜⵎⴰⵣⵉⵖⵜ', code: 'taq_Tfng' },
  { name: 'Tok Pisin', native: 'Tok Pisin', code: 'tpi_Latn' },
  { name: 'Tswana', native: 'Setswana', code: 'tsn_Latn' },
  { name: 'Tsonga', native: 'Xitsonga', code: 'tso_Latn' },
  { name: 'Turkmen', native: 'Türkmençe', code: 'tuk_Latn' },
  { name: 'Tumbuka', native: 'Chitumbuka', code: 'tum_Latn' },
  { name: 'Twi', native: 'Twi', code: 'twi_Latn' },
  { name: 'Tamazight (Tifinagh)', native: 'ⵜⴰⵎⴰⵣⵉⵖⵜ', code: 'tzm_Tfng' },
  { name: 'Umbundu', native: 'Umbundu', code: 'umb_Latn' },
  { name: 'Venetian', native: 'Vèneto', code: 'vec_Latn' },
  { name: 'Waray', native: 'Winaray', code: 'war_Latn' },
  { name: 'Yiddish', native: 'ייִדיש', code: 'ydd_Hebr' },
];

/** Number of language/script variants in the official NLLB inventory. */
export const NLLB_OFFICIAL_LANGUAGE_COUNT = 202;

export const NLLB_FLORES: Record<string, string> = {
  ...Object.fromEntries(NLLB_LANGUAGE_CATALOG.map((language) => [language.name, language.code])),
  // Backwards-compatible alias for older saved selections/history entries.
  Chinese: 'zho_Hans',
};
